# Generated by Django 2.1 on 2020-03-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Time')),
                ('Pressure', models.FloatField(verbose_name='Pressure')),
                ('Humidity', models.FloatField(verbose_name='Humidity')),
                ('TempIns', models.FloatField(verbose_name='TempIns')),
                ('TempWork', models.FloatField(verbose_name='TempWork')),
                ('pH', models.FloatField(verbose_name='pH')),
                ('Weight', models.FloatField(verbose_name='Weight')),
                ('FlowRate', models.FloatField(verbose_name='FlowRate')),
                ('CO2', models.FloatField(verbose_name='CO2')),
            ],
        ),
    ]
