# Generated by Django 2.2.8 on 2020-03-22 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200322_0230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('Time', models.DateTimeField(auto_now_add=True, db_index=True, primary_key=True, serialize=False, verbose_name='Time')),
                ('Pressure', models.FloatField(verbose_name='Pressure')),
                ('Humidity', models.FloatField(verbose_name='Humidity')),
                ('TempIns', models.FloatField(verbose_name='TempIns')),
                ('TempWork', models.FloatField(verbose_name='TempWork')),
                ('pH', models.FloatField(verbose_name='pH')),
                ('Weight', models.FloatField(verbose_name='Weight')),
                ('FlowRate', models.FloatField(verbose_name='FlowRate')),
                ('CO2', models.FloatField(verbose_name='CO2')),
            ],
        ),
        migrations.CreateModel(
            name='Ustavki',
            fields=[
                ('Time', models.DateTimeField(auto_now_add=True, db_index=True, primary_key=True, serialize=False, verbose_name='Time')),
                ('Pressure', models.FloatField(verbose_name='Pressure')),
                ('Humidity', models.FloatField(verbose_name='Humidity')),
                ('TempIns', models.FloatField(verbose_name='TempIns')),
                ('TempWork', models.FloatField(verbose_name='TempWork')),
                ('pH', models.FloatField(verbose_name='pH')),
                ('Weight', models.FloatField(verbose_name='Weight')),
                ('FlowRate', models.FloatField(verbose_name='FlowRate')),
                ('CO2', models.FloatField(verbose_name='CO2')),
            ],
        ),
    ]
