# Generated by Django 2.2.8 on 2020-03-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_error_ustavki'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Time')),
                ('Type', models.CharField(max_length=20, verbose_name='Type')),
                ('Marker', models.CharField(choices=[('s', 'Start'), ('f', 'Finish')], max_length=1)),
                ('Error', models.CharField(default='', editable=False, max_length=50, null=True, verbose_name='Log')),
            ],
        ),
    ]
