# Generated by Django 2.2.8 on 2020-03-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='Error',
            field=models.CharField(default='', editable=False, max_length=100, null=True, verbose_name='Log'),
        ),
    ]
